// Code generated by Axiom CLI; DO NOT EDIT.
package axiom;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * AxiomContext — the single injection point for platform capabilities (ADR-001).
 *
 * <p>A node receives one {@code AxiomContext} per invocation and reaches every
 * platform capability through it:
 * <pre>
 *   String key = ax.secrets().get("OPENAI_KEY").orElse("");
 *   var nodes  = ax.reflection().flow().nodes();
 * </pre>
 *
 * <p>Node code never talks to the platform directly — capabilities are
 * consolidated here to prevent signature drift across SDK versions (ADR-001).
 * All capability types are nested so the whole contract lives in one file.
 */
public interface AxiomContext {

    Logger log();

    Secrets secrets();

    String executionId();

    String flowId();

    String tenantId();

    Reflection reflection();

    Mutation mutation();

    // ── Tenant-safe telemetry (ADR-073) ─────────────────────────────────────
    // ADR-073 (2026-06-09): node telemetry is NOT a method on this interface, on
    // purpose. Adding one would break every package's committed AxiomContext test
    // double (durable-test re-push regression). Instead use the static accessor:
    //
    //   AxiomContext.telemetryOf(ax).addEvent("cache_hit", Map.of("size", "42"));
    //
    // In production the carrier buffers items onto NodeResponse.telemetry and the
    // sidecar (the SOLE collector egress) re-emits them under node.invoke with the
    // authoritative tenant_id — node code never reaches the collector and cannot
    // forge trace_id/parent. Under `axiom dev` (no sidecar) it degrades to no-op,
    // exactly like log() in a no-collector cluster.

    /** The tenant-safe telemetry surface (ADR-073). All calls buffer in-process
     *  and are flushed to the sidecar on handler return. */
    interface Telemetry {
        /** Record a named event (with optional attributes) on the node's span. */
        void addEvent(String name, Map<String, String> attrs);
        /** Add value to a named custom counter (sidecar Meter, ADR-070). */
        void counter(String name, double value, Map<String, String> attrs);
        /** Record value into a named custom histogram. */
        void histogram(String name, double value, Map<String, String> attrs);

        default void addEvent(String name) { addEvent(name, Map.of()); }
        default void counter(String name, double value) { counter(name, value, Map.of()); }
        default void histogram(String name, double value) { histogram(name, value, Map.of()); }
    }

    /** Implemented by the production AxiomContext so {@link #telemetryOf} can
     *  reach the per-invocation buffer without adding a method to AxiomContext
     *  (which would break existing test doubles). */
    interface TelemetryCarrier {
        Telemetry axiomTelemetry();
    }

    /** Returns the tenant-safe telemetry surface for this invocation (ADR-073).
     *  A static accessor — NOT an interface method — so it is non-breaking for
     *  existing node code and test doubles. No-op when the context does not carry
     *  a telemetry buffer (e.g. under `axiom dev`). */
    static Telemetry telemetryOf(AxiomContext ax) {
        if (ax instanceof TelemetryCarrier c) {
            Telemetry t = c.axiomTelemetry();
            if (t != null) return t;
        }
        return NOOP_TELEMETRY;
    }

    /** Shared no-op telemetry used under `axiom dev` / for non-carrier contexts. */
    Telemetry NOOP_TELEMETRY = new Telemetry() {
        @Override public void addEvent(String name, Map<String, String> attrs) {}
        @Override public void counter(String name, double value, Map<String, String> attrs) {}
        @Override public void histogram(String name, double value, Map<String, String> attrs) {}
    };

    // ── Logging & secrets ───────────────────────────────────────────────────

    /** Structured logger pre-configured for a single node invocation. */
    interface Logger {
        void debug(String msg, Map<String, String> attrs);
        void info(String msg, Map<String, String> attrs);
        void warn(String msg, Map<String, String> attrs);
        void error(String msg, Map<String, String> attrs);

        default void debug(String msg) { debug(msg, Map.of()); }
        default void info(String msg)  { info(msg, Map.of()); }
        default void warn(String msg)  { warn(msg, Map.of()); }
        default void error(String msg) { error(msg, Map.of()); }
    }

    /**
     * Typed result of {@link Secrets#status}  — ADR-156.
     *
     * <p>{@code get(name)} alone returns {@code Optional.empty()} both when a
     * secret was revoked after execution start and when it was never
     * configured at all — a node cannot tell "re-authorize this credential"
     * from "check axiom.yaml" from that result alone. Use {@code status()}
     * when the distinction matters.
     */
    enum SecretStatus {
        /** The secret currently resolves to a value; get(name) returns it. */
        AVAILABLE,
        /** The secret existed in this execution's initial snapshot but no
         *  longer resolves against the live vault — it was deleted or
         *  revoked after the execution started. get(name) returns empty. */
        REVOKED,
        /** The secret was never present for this node — never configured by
         *  the tenant, or (for a non-owned node) not authorized. get(name)
         *  returns empty, identically to REVOKED. */
        UNSET,
    }

    /** Read-only access to tenant secrets resolved by the platform. */
    interface Secrets {
        Optional<String> get(String name);

        /** Returns the typed status of a declared secret — ADR-156.
         *  Distinguishes SecretStatus.REVOKED (declared, existed at
         *  execution start, no longer resolvable) from SecretStatus.UNSET
         *  (never configured) — a distinction get alone cannot make since
         *  both return an empty Optional.
         *
         *  <p>ADR-156 (2026-07-20): a {@code default} method, not an abstract
         *  one, so the accessor stays BACKWARD-COMPATIBLE (and Secrets stays a
         *  functional interface usable as a lambda) — an abstract member would
         *  break every existing node's hand-written Secrets test double at
         *  compile time. The platform's MapSecrets overrides it with the real
         *  Available/Revoked/Unset distinction; an implementer that only
         *  provides get inherits this default (AVAILABLE when present, else
         *  UNSET), never a false REVOKED. */
        default SecretStatus status(String name) {
            return get(name).isPresent() ? SecretStatus.AVAILABLE : SecretStatus.UNSET;
        }
    }

    // ADR-129 (2026-07-11): agentic memory (ax.agent().memory()) is out of
    // scope for beta and has been removed from the node SDK entirely — a
    // shared marketplace node's memory proxy stamped the deploy-time
    // publisher tenant, letting unrelated tenants composing the same node
    // read each other's memory. Removing the client surface here closes the
    // reachable path at compile time. The backend (internal/memory,
    // proto/memory, MemoryService) is retained for post-beta.

    // ── Flow reflection (ADR-050 / ADR-055) ─────────────────────────────────

    /** A node in the running flow graph. gridCol/gridRow are the ADR-086
     *  coarse-grid cell (column = flow depth, row = parallel lane). */
    record ReflectionNode(
        int instanceId, String nodeUlid, String name, String packageName,
        String packageVersion, String nodeType, String inputMessageName,
        String outputMessageName, String canvasNodeId, int gridCol, int gridRow) {}

    /** ADR-055 / GAP-4: agent-readable digest of an edge's dispatch condition. */
    record ConditionSummary(String field, String op, List<String> operands) {}

    /** An edge in the running flow graph. {@code conditionSummary} is null when the edge is unconditional. */
    record ReflectionEdge(
        int srcInstance, int dstInstance, String canvasEdgeId, boolean hasCondition,
        boolean hasAdapter, int maxIterations, ConditionSummary conditionSummary) {}

    /** The executing position within the (possibly nested) flow. */
    record FlowPosition(
        int currentInstance, int depth, Map<Integer, Integer> loopIterations,
        List<String> subflowStackGraphIds) {}

    /** Read-only view of the running flow graph. */
    interface FlowReflection {
        List<ReflectionNode> nodes();
        List<ReflectionEdge> edges();
        List<ReflectionEdge> loopEdges();
        FlowPosition position();
        String graphId();
    }

    interface Reflection {
        FlowReflection flow();
    }

    // ── Flow mutation (ADR-051 / ADR-054) ───────────────────────────────────

    /** Canvas placement for a mutation-added node. ADR-086: set gridCol/gridRow
     *  to place the node at a coarse-grid cell (the worker derives pixels;
     *  grid takes precedence over x/y). */
    record CanvasPosition(double x, double y, int gridCol, int gridRow) {
        /** Pixel-only convenience; grid cell defaults to (0,0). */
        public CanvasPosition(double x, double y) { this(x, y, 0, 0); }
    }

    /** ADR-054: a conditional dispatch for a mutation-added edge. */
    record EdgeCondition(String op, String field, String value) {}

    /** Buffered, additive mutation of the running flow graph. */
    interface FlowMutation {
        int addNode(String packageName, String packageVersion, CanvasPosition canvasPosition);
        void addEdge(int srcInstance, int dstInstance, EdgeCondition condition);
    }

    interface Mutation {
        FlowMutation flow();
    }
}
